- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present

- name: Install kuberneties with k3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure kubectl symlink exists
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
    force: yes

- name: Set kubeconfig permission
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'

- name: Verify k3s service
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: yes
