---
- name: Create and Configure VM
  hosts: windows
  gather_facts: false
  vars_files:
    - groups/vars.yml

  tasks:
    - name: Create and configure VM
      import_tasks: tasks/win_create_and_configure_vm.yml

    - name: Attach Ubuntu ISO and Start VM
      import_tasks: tasks/win_add_ubuntu_and_startvm.yml

...
