---
- name: Verify VM exists on target
  hosts: windows
  gather_facts: false

  tasks:
    - name: Verify VM installation block
      block:
        - name: Check if Oracle VM is installed
          ansible.builtin.win_command: powershell -Command "Get-Item 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' -ErrorAction SilentlyContinue"
          register: vm_check
          ignore_errors: true
          failed_when: false
          changed_when: false

        - name: Debug VM presence
          ansible.builtin.debug:
            msg: "Oracle VM is already installed at C:\Program Files\Oracle\VirtualBox\VBoxManage.exe"
          when: vm_check.rc == 0

        - name: Fail if Oracle VM is not found
          ansible.builtin.debug:
            msg: "Oracle VM is not installed on the target machine."
          when: vm_check.rc != 0

        - name: Set fact for VM installation status
          ansible.builtin.set_fact:
            vm_installed: "{{ vm_check.rc == 0 }}"
        
        - name: Copy files to target hosts
          ansible.builtin.win_copy:
             src: /path/to/local/files/
             dest: C:\path\to\remote\files\
          when: not vm_installed

        - name: Install oracle vm on windows
          ansible.builtin.win_command: powershell -Command "Start-Process -FilePath 'C:\path\to\oracle_vm_installer.exe' -ArgumentList '/silent' -Wait"
          when: not vm_installed
          register: vm_install
          ignore_errors: true
          failed_when: vm_install.rc != 0
          changed_when: vm_install.rc == 0

